<a href="https://colab.research.google.com/github/WFVieira-hub/Met_Matematicos/blob/master/Aula_02_Met_matematicos_ago_18_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Primeiros comanados
print("Hello word")

Hello word


In [ ]:
# Laço for começa com zero obs: não tem and ---> (identação)
for k in range(2):
  for i in range(2):
    for j in range(2):
      print('k=',k,'i=',i,'j=',j)
      #print('===================')
    #print('==================')
  print('==================')

k= 0 i= 0 j= 0
k= 0 i= 0 j= 1
k= 0 i= 1 j= 0
k= 0 i= 1 j= 1
k= 1 i= 0 j= 0
k= 1 i= 0 j= 1
k= 1 i= 1 j= 0
k= 1 i= 1 j= 1


In [ ]:
x=[] # lista de valores, nome, matrix, ...
w=[] # Lista dentro de outra lista
for i in range(3):
  for j in range(3):
    x.append(j)
  w.append(x)
print(w)

y=[] # Lista dentro de outra lista
for i in range(3):
  x=[] # reinia a lista x para cada novo elemento i
  for j in range(3):
    x.append(j)
  y.append(x)
print(y)

[[0, 1, 2, 0, 1, 2, 0, 1, 2], [0, 1, 2, 0, 1, 2, 0, 1, 2], [0, 1, 2, 0, 1, 2, 0, 1, 2]]
[[0, 1, 2], [0, 1, 2], [0, 1, 2]]


In [ ]:
import pandas as pd
import numpy as np
df=pd.DataFrame(y) # conferteu em data frame
df[3]=[1,2,3]      # adiciona a coluna de resultados 
mat=np.array(y)    # formato de calculo
mat[0,1]=10
print(df)
print('------------------')
print(mat)

   0  1  2  3
0  0  1  2  1
1  0  1  2  2
2  0  1  2  3
------------------
[[ 0 10  2]
 [ 0  1  2]
 [ 0  1  2]]


   0  1  2
0  0  1  2
1  0  1  2
2  0  1  2
