<a href="https://colab.research.google.com/github/WFVieira-hub/Met_Matematicos/blob/master/Aula_02_Met_matematicos_ago_25_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Primeiros comanados
print("Hello word")

Hello word


In [2]:
# Laço for começa com zero obs: não tem and ---> (identação)
for k in range(2):
  for i in range(2):
    for j in range(2):
      print('k=',k,'i=',i,'j=',j)
      #print('===================')
    #print('==================')
  print('==================')

k= 0 i= 0 j= 0
k= 0 i= 0 j= 1
k= 0 i= 1 j= 0
k= 0 i= 1 j= 1
k= 1 i= 0 j= 0
k= 1 i= 0 j= 1
k= 1 i= 1 j= 0
k= 1 i= 1 j= 1


In [3]:
x=[] # lista de valores, nome, matrix, ...
w=[] # Lista dentro de outra lista
for i in range(3):
  for j in range(3):
    x.append(j)
  w.append(x)
print(w)

y=[] # Lista dentro de outra lista
for i in range(3):
  x=[] # reinia a lista x para cada novo elemento i
  for j in range(3):
    x.append(j)
  y.append(x)
print(y)

[[0, 1, 2, 0, 1, 2, 0, 1, 2], [0, 1, 2, 0, 1, 2, 0, 1, 2], [0, 1, 2, 0, 1, 2, 0, 1, 2]]
[[0, 1, 2], [0, 1, 2], [0, 1, 2]]


In [4]:
import pandas as pd
import numpy as np
df=pd.DataFrame(y) # conferteu em data frame
df[3]=[1,2,3]      # adiciona a coluna de resultados 
mat=np.array(y)    # formato de calculo
mat[0,1]=10
print(df)
print('------------------')
print(mat)

   0  1  2  3
0  0  1  2  1
1  0  1  2  2
2  0  1  2  3
------------------
[[ 0 10  2]
 [ 0  1  2]
 [ 0  1  2]]


In [8]:
# Aula 02
n=4
y=[] # Lista dentro de outra lista
for i in range(n):
  x=[] # reinia a lista x para cada novo elemento i
  for j in range(n):
    x.append(j)
  y.append(x)
print(y)
#--------------------------------------
# Criar função
#--------------------------------------
def Lista(nn):
  y=[] # Lista dentro de outra lista
  for i in range(nn):
    x=[] # reinia a lista x para cada novo elemento i
    for j in range(nn):
      x.append(j)
    y.append(x)
  return y

w=Lista(6) # função criada nn=6
print(w)


[[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3]]
[[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]]


In [10]:
# If teste logico

m=4 # item avaliado
if(m>2):
  print('valor maior que 2')
else:
  print('valor menor ou igual que 2')
print('-----------')

m=10
if(m>7):
  print('valor maior que 7')
elif(m>5):
  print('valor entre 7 e 5')
else:
  print('valor menor ou igual a 7')


valor maior que 2
-----------
valor maior que 7


In [11]:
# while

mm=10
cont=0
while(cont<mm):
  cont=cont+1
  print(cont)

1
2
3
4
5
6
7
8
9
10
